# Generated by Django 3.2.6 on 2021-09-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.OneToOneField(default=4526, on_delete=django.db.models.deletion.CASCADE, to='orders.customer'),
            preserve_default=False,
        ),
    ]
