# Generated by Django 3.2.6 on 2021-09-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_is_exclusive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_exclusive',
        ),
    ]
