# Generated by Django 3.2.6 on 2021-09-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_is_exclusive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=482, upload_to='categories/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
