# Generated by Django 3.2.6 on 2021-09-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ability',
            field=models.IntegerField(),
        ),
    ]
